package codegen

import (
	"fmt"
	"log"

	. "github.com/dave/jennifer/jen"
	"github.com/endigma/toucan/schema"
)

type Generator struct {
	Schema *schema.Schema
	Output *OutputConfig
}

type OutputConfig struct {
	Path    string `validate:"required"`
	Package string `validate:"required"`
}

func NewGenerator(schema *schema.Schema, out *OutputConfig) *Generator {
	return &Generator{Output: out, Schema: schema}
}

func (gen *Generator) Generate() error {
	outFile := NewFile(gen.Output.Package)
	outFile.PackageComment("Code generated by toucan. DO NOT EDIT.")
	outFile.Line()

	// Generate resources
	for _, resource := range gen.Schema.Resources {
		if err := generateResource(outFile.Group, gen.Schema.Actor, resource); err != nil {
			log.Fatal(err)
		}
	}

	// Generate global resolver
	generateGlobalResolver(outFile.Group, gen.Schema.Resources)

	// Generate global authorizer
	generateGlobalAuthorizer(outFile.Group, gen.Schema.Actor, gen.Schema.Resources)

	err := outFile.Save(gen.Output.Path + gen.Output.Package + ".go")
	if err != nil {
		return fmt.Errorf("failed to save file: %w", err)
	}

	return nil
}

func generateResource(group *Group, actor schema.Model, resource schema.ResourceSchema) error {
	group.Commentf("resource `%s`", resource.Name).Line()

	// Generate enums
	if err := generateResourceTypes(group, resource); err != nil {
		return err
	}

	// Generate resolver
	if err := generateResourceResolver(group, actor, resource); err != nil {
		return err
	}

	// Generate resolver
	if err := generateResourceAuthorizer(group, actor, resource); err != nil {
		return err
	}

	return nil
}
