name: golangci-lint
on:
  ["push", "pull_request"]
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  golangci-lint:
    strategy:
      matrix:
        go: ["1.19", "1.20"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.4.0
        with:
          version: v1.52.2
          # skip cache because of flaky behaviors
          skip-build-cache: true
          skip-pkg-cache: true
          args: "--timeout 5m"
